services:
  backend:
      build:
        context: ./backend/
        dockerfile: ./Dockerfile
      ports:
        - '8000:8000'
      volumes:
        - ./backend/main.py:/backend/main.py
      command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  frontend:
      build:
        context: ./frontend/
        dockerfile: ./Dockerfile
      ports:
        - "5173:5173"
      volumes:
        - ./frontend/src:/frontend/src
        - ./frontend/static:/frontend/static
        - ./frontend/vite.config.js:/frontend/vite.config.js
        - ./frontend/tsconfig.json:/frontend/tsconfig.json
        - ./frontend/svelte.config.js:/frontend/svelte.config.js
      command: npm run dev -- --host
